[package]
edition = "2021"
name = "tui-rsx"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ratatui = {version = "0.20.1", default-features = false}
tui-rsx-macros = {path = "../tui-rsx-macros"}
